Scenario : Tourist registration

Given : New Ilp page
When  : I enter data in all mandatory fields	 
And   : Click add button 
Then  : It should add Tourist


                                                                                                                                                                                                                                       
===============================================================================================================================================================================================================================================
| Test case ID |                Test case description                 |                         Test steps                        |                      Expected result                       |                  Actual result                  |  Status  |
|==============|======================================================|===========================================================|============================================================|=================================================|==========|
| 1.1          | Check the functionality of Tour operator             | Type 's'                                                  | It should display all the tour oerators                    | Displaying all the tour operators               | Passed   |
|              | search box                                           |                                                           | starting with letter 's' in the list                       | in the list                                     |          |
|--------------|------------------------------------------------------|-----------------------------------------------------------|------------------------------------------------------------|-------------------------------------------------|----------|
| 1.2          | Check the functionality of Permit date               | Select any date                                           | It should select date                                      | Selecting date                                  | Passed   |
|              | from date picker                                     |                                                           |                                                            |                                                 |          |
|--------------|------------------------------------------------------|-----------------------------------------------------------|------------------------------------------------------------|-------------------------------------------------|----------|
| 1.3          | Check the functionality of Permit date               | Select any date                                           | It should select date                                      | Selecting date                                  | Passed   |
|              | to date picker                                       |                                                           |                                                            |                                                 |          |
|--------------|------------------------------------------------------|-----------------------------------------------------------|------------------------------------------------------------|-------------------------------------------------|----------|
| 1.4          | Check the functionality of Full name                 | Enter alphabets,special characters                        | It should accept only alphabets,spaces                     | Accepting alphabets along with                  | Resolved |
|              | text box                                             | and full stop                                             | and full stop                                              | special characters                              |          |
|--------------|------------------------------------------------------|-----------------------------------------------------------|------------------------------------------------------------|-------------------------------------------------|----------|
| 1.5          | Check the functionality of Gender drop               | Click on gender drop down list and                        | It should select select one gender at a time               | Selecting one gender at a time                  | Passed   |
|              | down list                                            | select any gender from the list                           |                                                            |                                                 |          |
|--------------|------------------------------------------------------|-----------------------------------------------------------|------------------------------------------------------------|-------------------------------------------------|----------|
| 1.6          | Check the functionality of Date of birth             | Click on date picker and select any                       | It should select date                                      | Selecting date                                  | Passed   |
|              | date picker                                          | date                                                      |                                                            |                                                 |          |
|--------------|------------------------------------------------------|-----------------------------------------------------------|------------------------------------------------------------|-------------------------------------------------|----------|
| 1.7          | Check the functionality of Age non editable          | Select date jul-20-2000 from                              | It should display 14                                       | Displaying 14                                   | Passed   |
|              | field                                                | date of birth picker                                      |                                                            |                                                 |          |
|--------------|------------------------------------------------------|-----------------------------------------------------------|------------------------------------------------------------|-------------------------------------------------|----------|
| 1.8          | Check the functinality of Nationality                | Click on nationality drop down list                       | It should select single country at a time                  | Selecting single country at a time              | Passed   |
|              | drop down list                                       | and select any country                                    |                                                            |                                                 |          |
|--------------|------------------------------------------------------|-----------------------------------------------------------|------------------------------------------------------------|-------------------------------------------------|----------|
| 1.9          | Check the functionality of State text box            | Enter any input                                           | It should accept only alphabets                            | Accepting only alphabets                        | Passed   |
|              |                                                      |                                                           |                                                            |                                                 |          |
|--------------|------------------------------------------------------|-----------------------------------------------------------|------------------------------------------------------------|-------------------------------------------------|----------|
| 2.0          | Check the funtionality of Phone number text box      | Enter alphanumeric and special characters                 | It should accept only numbers and symbols '+'              | Accepting numbers and all special               | Resolved |
|              |                                                      |                                                           | and '-'                                                    | characters                                      |          |
|--------------|------------------------------------------------------|-----------------------------------------------------------|------------------------------------------------------------|-------------------------------------------------|----------|
| 2.1          | Check the functionality of Passport number           | Enter alphanumeric and special characters                 | It should accept alphanumeric and symbols '-'              | Accepting alphanumerics and all special         | Failed   |
|              | text box                                             |                                                           | and '/'                                                    | characters                                      |          |
|--------------|------------------------------------------------------|-----------------------------------------------------------|------------------------------------------------------------|-------------------------------------------------|----------|
| 2.2          | Check the functionality of Passport validity         | Select any date                                           | It should select date                                      | Selecting date                                  | Passed   |
|              | date picker                                          |                                                           |                                                            |                                                 |          |
|--------------|------------------------------------------------------|-----------------------------------------------------------|------------------------------------------------------------|-------------------------------------------------|----------|
| 2.3          | Check the functionality of Visa number text box      | Enter alphanumeric data and special                       | It should accept alphanumeric and symbols '-'              | Accepting alphanumeric and special              | Resolved |
|              |                                                      | characters                                                | and '/'                                                    | characters                                      |          |
|--------------|------------------------------------------------------|-----------------------------------------------------------|------------------------------------------------------------|-------------------------------------------------|----------|
| 2.4          | Check the functionality of Visa validity             | Select any date                                           | It should select date                                      | Selecting date                                  | Passed   |
|              | date picker                                          |                                                           |                                                            |                                                 |          |
|--------------|------------------------------------------------------|-----------------------------------------------------------|------------------------------------------------------------|-------------------------------------------------|----------|
| 2.5          | Check the functionality of Address text area         | Enter any data                                            | It should accept input                                     | Accepting input                                 | Passed   |
|--------------|------------------------------------------------------|-----------------------------------------------------------|------------------------------------------------------------|-------------------------------------------------|----------|
| 2.6          | Check the functionality of Upload documents          | Click on button                                           | It should navigate to scanner documents page               | Naviagting to scanner documents page            | Passed   |
|              | button                                               |                                                           | which contains scanner and finish button                   |                                                 |          |
|--------------|------------------------------------------------------|-----------------------------------------------------------|------------------------------------------------------------|-------------------------------------------------|----------|
| 2.6.1        | Check the functionality of Scanner button            | Connect scanner and click on scanner button               | It should scan the documents and should display            | Scanning documents and showing preview          | Passed   |
|              |                                                      |                                                           | it on the page                                             | on the page                                     |          |
|--------------|------------------------------------------------------|-----------------------------------------------------------|------------------------------------------------------------|-------------------------------------------------|----------|
| 2.6.2        | Check the functionality of Finish button             | Click on finish button after scanning                     | It should navigate back to new ILP page                    | Navigating back to new ILP page                 | Passed   |
|              |                                                      | documents                                                 |                                                            |                                                 |          |
|--------------|------------------------------------------------------|-----------------------------------------------------------|------------------------------------------------------------|-------------------------------------------------|----------|
| 2.7          | Check the functionality of Photo button              | Connect camera and click on photo button                  | It shoud diplay the view infront of camera                 | Showing the view infront of camera              | Passed   |
|--------------|------------------------------------------------------|-----------------------------------------------------------|------------------------------------------------------------|-------------------------------------------------|----------|
| 2.8          | Check the functionality of Add button                | Enter data in all mandatory fields and click              | It should add the tourist in the grid                      | Adding the tourist in the grid                  | Passed   |
|              |                                                      | on add button                                             |                                                            |                                                 |          |
|--------------|------------------------------------------------------|-----------------------------------------------------------|------------------------------------------------------------|-------------------------------------------------|----------|
| 2.9          | Check validations for all fields                     | Click on add button without entering data                 | It should display validation message                       | Displaying validation message                   | Passed   |
|              |                                                      | in all fields                                             |                                                            |                                                 |          |
|--------------|------------------------------------------------------|-----------------------------------------------------------|------------------------------------------------------------|-------------------------------------------------|----------|
| 3.0          | Check validations for all fields                     | Enter data in all fields and clear data and               | It should display validation message of all                | Not showing validation messages                 | Passed   |
|              |                                                      | click on add button                                       | cleared fields                                             |                                                 |          |
|--------------|------------------------------------------------------|-----------------------------------------------------------|------------------------------------------------------------|-------------------------------------------------|----------|
| 3.1          | Check the functionality of Is finished adding        | Click on check box                                        | It should get checked                                      | Is finished adding checked                      | Passed   |
|              | check box                                            |                                                           |                                                            |                                                 |          |
|--------------|------------------------------------------------------|-----------------------------------------------------------|------------------------------------------------------------|-------------------------------------------------|----------|
| 3.2          | Check validations for Nationality drop down list     | Select India/Bhutan/Nepal from nationality                | It should display ILP not required validation              | Displaying ILP not required validation          | Passed   |
|              |                                                      | drop down list                                            | message and add button should be in disable mode           | message and add button is in disable mode       |          |
|--------------|------------------------------------------------------|-----------------------------------------------------------|------------------------------------------------------------|-------------------------------------------------|----------|
| 3.3          | Check validations for Nationality drop down list     | Select Nigeria from nationality drop down list            | It should display not eligible for ILP validation          | Displaying not eligible for ILP validation      | Passed   |
|              |                                                      |                                                           | message and add button should be in disable mode           | and add button is in disable mode               |          |
|--------------|------------------------------------------------------|-----------------------------------------------------------|------------------------------------------------------------|-------------------------------------------------|----------|
| 3.4          | Check validtions for documents required countries    | Select Pakistan/Hong kong/Macau from nationality          | It should display approval required validation             | Displaying approval required validation         | Passed   |
|              |                                                      | drop down list                                            | message and scan MHA/MEA documents button and upload       | message and both scan and upload buttons        |          |
|              |                                                      |                                                           | button should be visible                                   | were enabled                                    |          |
|--------------|------------------------------------------------------|-----------------------------------------------------------|------------------------------------------------------------|-------------------------------------------------|----------|
| 3.5          | Check validations for same visa and passport         | Add tourist .Now again add another tourist with           | It should display validation message as tourist            | Adding tourist with same passport number        | Passed   |
|              | number                                               | passport and visa number same as first tourist            | already added with the given passport number               | and visa number in the group twice              |          |
|              |                                                      |                                                           | and visa number in the group                               |                                                 |          |
|--------------|------------------------------------------------------|-----------------------------------------------------------|------------------------------------------------------------|-------------------------------------------------|----------|
| 3.6          | Check validations for passport validity and          |                                                           |                                                            |                                                 |          |
|              | visa validity date                                   |                                                           |                                                            |                                                 |          |
|--------------|------------------------------------------------------|-----------------------------------------------------------|------------------------------------------------------------|-------------------------------------------------|----------|
| 3.7          | Check for duplicate tourists                         | Search any tourist and click on tourist in the grid       | Update button should be disabled after exiting             | Update button is enabled and when we click      | Passed   |
|              |                                                      | and select check box and click on exit ilp button         | ILP                                                        | on update button adding duplicate tourist       |          |
|              |                                                      | and click on update button                                |                                                            | in the grid                                     |          |
|--------------|------------------------------------------------------|-----------------------------------------------------------|------------------------------------------------------------|-------------------------------------------------|----------|
| 3.8          | Check validation for Nepal tourists                  | Select Nepal from nationality drop down                   | Visa number, Visa issued in, Visa validity date should     | Visa number, Visa issued in, Visa validity date | Passed   |
|              |                                                      |                                                           | be disabled and passport field label should be passport/ID | fields were disabled and passport field label   |          |
|              |                                                      |                                                           |                                                            | changed to ID/Passport                          |          |
|--------------|------------------------------------------------------|-----------------------------------------------------------|------------------------------------------------------------|-------------------------------------------------|----------|
| 3.9          | Check validation for Refugee countries               | Select any refugee country from the nationality           | Visa number and visa validity date should be disabled      |                                                 |          |
|              |                                                      | drop down list                                            | and passport field label should be passport/ID             |                                                 |          |
|--------------|------------------------------------------------------|-----------------------------------------------------------|------------------------------------------------------------|-------------------------------------------------|----------|
| 4.0          | Check the functionality of Arrived from text box     | Enter any input                                           | It should accept input                                     | Accepting input                                 | Passed   |
|--------------|------------------------------------------------------|-----------------------------------------------------------|------------------------------------------------------------|-------------------------------------------------|----------|
| 4.1          | Check the functionality of Purpose of visit text     | Enter any input in the text area                          | It should accept input                                     | Accepting input                                 | Passed   |
|              | area                                                 |                                                           |                                                            |                                                 |          |
|--------------|------------------------------------------------------|-----------------------------------------------------------|------------------------------------------------------------|-------------------------------------------------|----------|
| 4.2          | Check the functionality of Visa issued in drop       | Click on drop down list and select any country name       | It should display all the nationalities in the list        | Displaying all countries in the list and        | Passed   |
|              | down list                                            | from the list                                             | and should select one country at a time                    | selecting one country name at a time            |          |
|--------------|------------------------------------------------------|-----------------------------------------------------------|------------------------------------------------------------|-------------------------------------------------|----------|
| 4.3          | Check visa validity date for Nepal/refugee countries | Retrieve nepal/refugee country provisional RAP in metro   | It should not insert visa validity date for nepal/refugee  | Inserting visa validity date for nepal/refugee  | Failed   |
|              |                                                      | app and update passport validity date and checck database | country tourists                                           | tourists after updating passport validity date  |          |
|--------------|------------------------------------------------------|-----------------------------------------------------------|------------------------------------------------------------|-------------------------------------------------|----------|







